### ISSUE TITLE
Kanban Board Review

### ISSUE THREAD

**Issue by ulisesedu7** [ulisesedu7/Catalog-Of-My-Things#22]
Hi reviewer, we're a team of 3 people divided this way:
Team Member #1 = @ulisesedu7 
Team Member #2 = @David-Verde 
Team Member #3 = @desorgui 

Here's the link for the project: 
https://github.com/users/ulisesedu7/projects/2

**Comment by m05e5** [comment]
# Status: ✔️ Project Approved ✔️ 

Hello @ulisesedu7 , @desorgui , @David-Verde  🔥 

Good job on With your Kanban board. Well Done.
Your project is complete! There is nothing else to say other than... it's time to get to the next milestone :shipit:
Congratulations! 🎉

![goodjob](https://user-images.githubusercontent.com/60631456/130260474-3c2d5e5c-96df-43de-a0db-8d0059c10862.gif)

Now you can merge this branch 🚀 

_m05e5_

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ulisesedu7** [comment]
@m05e5 Thank you very much!
